packageExtensions:
  '@atls-ui-generators/icons@*':
    peerDependencies:
      glob: '*'
  swiper@*:
    peerDependencies:
      react: ^17.0.1
  '@atls-ui-parts/layout@*':
    dependencies:
      csstype: '*'
  '@atls-ui-parts/link@*':
    dependencies:
      '@emotion/css': '*'

yarnPath: .yarn/releases/yarn-0.0.1-git.20230217.hash-56aa982.cjs
