packageExtensions:
  '@apollo/client@*':
    dependencies:
      '@types/zen-observable': '*'
    peerDependencies:
      react-dom: '*'
  '@apollo/link-error@*':
    peerDependencies:
      graphql: '*'
      react: '*'
      react-dom: '*'
  '@apollo/react-ssr@*':
    peerDependencies:
      graphql: '*'
      react: '*'
      react-dom: '*'
  '@atls/next-app-with-apollo@*':
    dependencies:
      '@types/zen-observable': '*'
    peerDependencies:
      next: '*'
  '@atls/next-app-with-emotion@*':
    peerDependencies:
      next: '*'
  '@atls-ui-parts/layout@*':
    dependencies:
      csstype: '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  '@emotion/styled@*':
    dependencies:
      '@emotion/react': '*'

plugins:
  - path: .yarn/plugins/@atls/plugin-essentials.cjs
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.0.0.cjs
