packageExtensions:
  "@atls-ui-generators/icons@*":
    peerDependencies:
      glob: "*"
  "@atls-ui-parts/layout@*":
    dependencies:
      csstype: "*"
  "@atls-ui-parts/link@*":
    dependencies:
      "@emotion/css": "*"
  swiper@*:
    peerDependencies:
      react: ^17.0.1

yarnPath: .yarn/releases/yarn-remote.cjs
