packageExtensions:
  '@atls/react-payment-widget@*':
    dependencies:
      'styled-system': '5.1.5'
    peerDependencies:
      'react-dom': '*'
  '@atls-ui-generators/icons@*':
    peerDependencies:
      glob: '*'
  '@atls-ui-parts/layout@*':
    dependencies:
      csstype: '*'
  '@atls-ui-parts/link@*':
    dependencies:
      '@emotion/css': '*'
  swiper@*:
    peerDependencies:
      react: '18'

yarnPath: .yarn/releases/yarn-remote.cjs

enableGlobalCache: false
