packageExtensions:
  '@atls-ui-generators/icons@*':
    peerDependencies:
      glob: '*'
  swiper@*:
    peerDependencies:
      react: ^17.0.1

yarnPath: .yarn/releases/yarn-0.0.1-git.20221107.hash-d21b699.cjs
