version: '3.8'

services:
  yarn:
    image: node:18.13
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn

  landing:
    image: node:18.13
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: yarn workspace @landing/renderer-entrypoint dev
    environment:
      - WP_ENDPOINT=https://wp.drumin.pro/graphql
    ports:
      - '3000:3000'

volumes:
  wordpress:
  db:
