const getUi = (itemId) => {
  if (itemId === 'courseOpeningTheRhythm')
    return {
      squareRotate: -4,
      squarePositionX: 2,
      squarePositionY: 2,
      squareRotateMobile: 0,
      squarePositionXMobile: 0,
      squarePositionYMobile: 0,
      circlePositionX: 175,
      circlePositionY: 121,
      circlePositionXMobile: 194,
      circlePositionYMobile: 83,
      rectangleRotate: 4,
      rectanglePositionX: 193,
      rectanglePositionY: 11,
      rectangleRotateMobile: 30,
      rectanglePositionXMobile: 95,
      rectanglePositionYMobile: 43,
      rectangleColor: 'transparentPurpleGradient',
    }
  if (itemId === 'courseSenseOfTime')
    return {
      squareRotate: 10,
      squarePositionX: 389,
      squarePositionY: 29,
      squareRotateMobile: 15,
      squarePositionXMobile: 188,
      squarePositionYMobile: 20,
      circlePositionX: 203,
      circlePositionY: 0,
      circlePositionXMobile: 78,
      circlePositionYMobile: 0,
      rectangleRotate: -8,
      rectanglePositionX: 2,
      rectanglePositionY: 172,
      rectangleRotateMobile: -15,
      rectanglePositionXMobile: 2,
      rectanglePositionYMobile: 104,
      rectangleColor: 'transparentBlueGradient',
    }
  if (itemId === 'courseFifthDimension')
    return {
      squareRotate: 0,
      squarePositionX: 400,
      squarePositionY: 0,
      squareRotateMobile: 0,
      squarePositionXMobile: 193,
      squarePositionYMobile: 0,
      circlePositionX: 0,
      circlePositionY: 113,
      circlePositionXMobile: 0,
      circlePositionYMobile: 0,
      rectangleRotate: -15,
      rectanglePositionX: 36,
      rectanglePositionY: 36,
      rectangleRotateMobile: -30,
      rectanglePositionXMobile: -6,
      rectanglePositionYMobile: 40,
      rectangleColor: 'transparentGreenGradient',
    }
  if (itemId === 'courseSeventhHeaven')
    return {
      squareRotate: 0,
      squarePositionX: 184,
      squarePositionY: 139,
      squareRotateMobile: 0,
      squarePositionXMobile: 190,
      squarePositionYMobile: 88,
      circlePositionX: 28,
      circlePositionY: 0,
      circlePositionXMobile: 0,
      circlePositionYMobile: 0,
      rectangleRotate: -15,
      rectanglePositionX: 215,
      rectanglePositionY: 42,
      rectangleRotateMobile: 30,
      rectanglePositionXMobile: 71,
      rectanglePositionYMobile: 44,
      rectangleColor: 'transparentPinkGradient',
    }
  if (itemId === 'courseConnacol')
    return {
      squareRotate: 15,
      squarePositionX: 385,
      squarePositionY: 99,
      squareRotateMobile: 30,
      squarePositionXMobile: 186,
      squarePositionYMobile: 15,
      circlePositionX: 203,
      circlePositionY: 0,
      circlePositionXMobile: 71,
      circlePositionYMobile: 0,
      rectangleRotate: -15,
      rectanglePositionX: 0,
      rectanglePositionY: 158,
      rectangleRotateMobile: -15,
      rectanglePositionXMobile: 0,
      rectanglePositionYMobile: 102,
      rectangleColor: 'transparentPurpleGradient',
    }
  if (itemId === 'coursePolyrhythmicKeys')
    return {
      squareRotate: 0,
      squarePositionX: 27,
      squarePositionY: 0,
      squareRotateMobile: 0,
      squarePositionXMobile: 2,
      squarePositionYMobile: 0,
      rectangleRotate: 10,
      rectanglePositionX: 211,
      rectanglePositionY: 29,
      rectangleRotateMobile: 30,
      rectanglePositionXMobile: 98,
      rectanglePositionYMobile: 41,
      rectangleColor: 'transparentPurpleGradient',
    }
  return {
    squareRotate: -4,
    squarePositionX: 2,
    squarePositionY: 2,
    squareRotateMobile: 0,
    squarePositionXMobile: 0,
    squarePositionYMobile: 0,
    circlePositionX: 175,
    circlePositionY: 121,
    circlePositionXMobile: 194,
    circlePositionYMobile: 83,
    rectangleRotate: 4,
    rectanglePositionX: 193,
    rectanglePositionY: 11,
    rectangleRotateMobile: 30,
    rectanglePositionXMobile: 95,
    rectanglePositionYMobile: 43,
    rectangleColor: 'transparentPurpleGradient',
  }
}

export { getUi }
