export const WRAPPER_WIDTH = 580

export const RIGHT_INDENT_BY_HOVER = 0
export const RIGHT_INDENT_DEFAULT = 20

export const LEFT_INDENT_BY_HOVER = 20
export const LEFT_INDENT_DEFAULT = 0

export const TRANSITION_DELAY = '0.3s'

export const ARROW_ICON_WIDTH_FOR_DESKTOP = [0, 104, 164]
export const ARROW_ICON_HEIGHT_FOR_DESKTOP = [0, 104, 164]
export const ARROW_ICON_WIDTH_FOR_MOBILE = 56
export const ARROW_ICON_HEIGHT_FOR_MOBILE = 14

export const INDENT_BETWEEN_ELEMENTS_FOR_MOBILE = 16
export const INDENT_BETWEEN_ELEMENTS_FOR_LAPTOP = 32
export const INDENT_BETWEEN_ELEMENTS_FOR_DESKTOP_HOVER_STATE = 30
export const INDENT_BETWEEN_ELEMENTS_FOR_DESKTOP_DEFAULT_STATE = 50
