const backgrounds = {
  blueGradient: 'linear-gradient(261.7deg, #5B68DF 14.84%, #020413 128.52%)',
  greenGradient: 'linear-gradient(263.11deg, #73E0A9 -4.32%, #03170D 98.56%)',
  pinkGradient: 'linear-gradient(263.61deg, #FF64BF -2.1%, #390725 127.32%)',
  blueWhiteGradient: 'linear-gradient(141.19deg, #60D5FA -31.03%, #CBF2FE 110.69%)',
  grayWhiteGradient: 'linear-gradient(138.39deg, #FBFBFD 4.86%, #B8C9D3 90.65%)',
  transparentPurpleGradient: 'linear-gradient(263.44deg, #9C65F2 -2.14%, #2D1652 107.82%)',
  transparentBlueGradient: 'linear-gradient(261.7deg, #5B68DF 14.84%, #020413 128.52%)',
  transparentGreenGradient: 'linear-gradient(263.11deg, #73E0A9 -4.32%, #03170D 98.56%)',
  transparentPinkGradient: 'linear-gradient(263.61deg, #FF64BF -2.1%, #390725 127.32%)',
  purpleBlueImageGradient: 'url("/img/bg-hero-main-page.png")',
  transparentPurpleBlueImageGradient: 'url("/img/bg-hero-course-page.png")',
  transparentBlueTurquoiseImageGradient: 'url("/img/bg-hero-feeling-of-time-page.png")',
  purpleBlueSmallImageGradient: 'url("/img/mobile-bg-hero-main-page.png")',
  blueTurquoiseSmallImageGradient: 'url("/img/mobile-bg-hero-feeling-of-time-page.png")',
  purpleBlueCirclesImage: 'url("/img/bg-middle-main-page.png")',
  blueTurquoiseCirclesImage: 'url("/img/bg-middle-feeling-of-time-page.png")',
  purpleBlueSemicircleImage: 'url("/img/bg-desktop-footer.png")',
  purpleBlueTwoSemicirclesSmallImage: 'url("/img/bg-mobile-footer.png")',
  blueTurquoiseSemicircleImage: 'url("/img/bg-footer-feeling-of-time-page.png")',
  blueTurquoiseTwoSemicirclesSmallImage: 'url("/img/bg-mobile-footer-feeling-of-time-page.png")',
  verticalTransparentToBlackGradient:
    'linear-gradient(360deg, #0F0C0C 0%, rgba(15, 12, 12, 0) 100%)',
  purpleBlueAngularGradient: 'url("/img/bg-contact-page.png")',
  transparentGreenBlueImageGradient: 'url("/img/bg-hero-fifth-dimension-page.png")',
  greenBlueSmallImageGradient: 'url("/img/mobile-bg-hero-fifth-dimension-page.png")',
  greenBlueCirclesImage: 'url("/img/bg-middle-fifth-dimension-page.png")',
  greenBlueSemicircleImage: 'url("/img/bg-footer-fifth-dimension-page.png")',
  greenBlueTwoSemicirclesSmallImage: 'url("/img/bg-mobile-footer-fifth-dimension-page.png")',
  progressLineWithBlackBackground: 'url("/img/progress-horizontal-section.png")',
  mobileProgressLineWithBlackBackground: 'url("/img/mobile-progress-section.png")',
}

export { backgrounds }
